---
title: "Handling folders of base called sequence output"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Preamble

This `base called sequence` vignette introduces how the sequence data prepared
by MinKNOW or Dorado may be processed in a simplified manner.

## Getting started with the canned dataset

The `rtqc` package is distributed with some simplified data.

```{r load_rtqc}
library(rtqc)

dorado_fastq_path <- get_bundled_path("fastq_pass")
bf <- basecalled_folder$new(dorado_fastq_path)
print(bf)
```

We can also process demultiplexed sequence collections

```{r load_multiplexed}
library(rtqc)

dorado_fastq_path <- get_bundled_path("barcoded_pass")
bf <- basecalled_folder$new(dorado_fastq_path)
print(bf)

bf$index()
```


```{r parse_fastq}

dorado_fastq_path <- get_bundled_path("fastq_pass")
single_fastq <- file.path(
  dorado_fastq_path, list.files(dorado_fastq_path)[1])
dorado_fastq_path <- get_bundled_path("fastq_pass")
rtqc::index_fastq(single_fastq, tempdir())
```
