# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rtqc_wrappers", use_symbols = TRUE, package_name = "rtqc")

#' @docType package
#' @usage NULL
#' @useDynLib rtqc, .registration = TRUE
NULL

index_fastq <- function(fq_path) .Call(wrap__index_fastq, fq_path)


# nolint end
