# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rtqc_wrappers", use_symbols = TRUE, package_name = "rtqc")

#' @docType package
#' @usage NULL
#' @useDynLib rtqc, .registration = TRUE
NULL

#' perform an index of fastq entry metadata
#' @export
index_fastq <- function(fq_path, dir) .Call(wrap__index_fastq, fq_path, dir)

#' perform an index of multiple fastq entry metadata
#' @export
index_fastq_list <- function(file_list, dir, threads) .Call(wrap__index_fastq_list, file_list, dir, threads)


# nolint end
