
#' R6 Class for harvesting information from a sequence_set object
#'
#' @description
#' `sequence_set` class provides an infrastructure for working with sets of
#' sequence that have been generated by the base calling software. This class
#' interacts with the sequence_set to emit data as per sets of rules and
#' characteristics; filters belong within the sequencing_set object
#'
#' looking for e.g.
#' harv <- harvester$new(seqset$length_filter()$quality_filter())
#' harv$to_fastq()
