
#' R6 Class for handling a logical set of sequence data
#'
#' @description
#' `sequence_set` class provides an infrastructure for working with sets of
#' sequence that have been generated by the base calling software.
#'
#' @import R6
#'
#' @export
sequence_set <- R6::R6Class(
  classname = "sequence_set",

  public = list(
    initialize = function() {

    },

    fastq_ingress = function(fastq_file) {

    },

    sam_bam_ingress = function(bam_file) {

    }
  ),

  private = list(

  )

)
