
#' R6 Class for handling a logical set of sequence data
#'
#' @description
#' `sequence_set` class provides an infrastructure for working with sets of
#' sequence that have been generated by the base calling software.
#'
#' @import R6
#'
#' @export
sequence_set <- R6::R6Class(
  classname = "sequence_set",

  public = list(
    #' @description
    #' Constructor method for `sequence_set` requires just a path to the
    #' cache_directory that will be populated with parquet files that
    #' summarise the sequence collection being processed
    #'
    #' @param cache_dir a fully qualified path to a cache directory
    initialize = function(cache_dir) {
      private$cache_dir <- cache_dir
    },

    #' @description
    #' allowing for the real time generation of sequence data and accommodating
    #' the background processing of indices, this method just pokes the system
    #' to ensure that the latest changes within the `cache_dir` are understood
    #' and that data held is up-to-date.
    sync = function() {
      private$get_arrow()
    }
  ),

  private = list(
    cache_dir = NULL,

    get_arrow = function() {
      arrow <- form_arrow(private$cache_dir)
    }
  )

)
